# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!

platform :ios, '9.0'

target 'Modularization' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'BeeHive'
  pod 'YTKNetwork'
  pod 'ReactiveObjC'
#  pod 'JLRoutes'
  pod 'ModuleA', :path => './ModuleA'
  pod 'ModuleB', :path => './ModuleB'
  pod 'ModuleC', :path => './ModuleC'
  pod 'QMUIKit'
  # Pods for Modularization

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
